export enum PERMISOS {
    USER_CREATE = 'user.create',
    USER_UPDATE = 'user.update',
    USER_DELETE = 'user.delete',
    USER_READ = 'user.read',
    USER_READ_All = 'user.read.all',
    ORGANIZACION_CREATE = 'organizacion.create',
    ORGANIZACION_UPDATE = 'organizacion.update',
    ORGANIZACION_DELETE = 'organizacion.delete',
    ORGANIZACION_READ = 'organizacion.read',
    ORGANIZACION_READ_All = 'organizacion.read.all',
    ROL_CREATE = 'rol.create',
    ROL_UPDATE = 'rol.update',
    ROL_DELETE = 'rol.delete',
    ROL_READ = 'rol.read',
    ROL_READ_All = 'rol.read.all',
    PERMISO_CREATE = 'permiso.create',
    PERMISO_UPDATE = 'permiso.update',
    PERMISO_DELETE = 'permiso.delete',
    PERMISO_READ = 'permiso.read',
    PERMISO_READ_All = 'permiso.read.all',
}
